# Generated by Django 4.2.5 on 2023-10-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SonBuenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('artistas', models.ManyToManyField(to='sonbuenos.artista')),
                ('genero', models.ManyToManyField(to='sonbuenos.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('duracion', models.DurationField(null=True)),
                ('fecha', models.DateField(null=True)),
                ('idSpotify', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonbuenos.entidadmusical')),
                ('genero', models.ManyToManyField(to='sonbuenos.genero')),
            ],
        ),
    ]
