# Generated by Django 4.2.4 on 2023-08-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artistas',
            new_name='Sonbuenos',
        ),
    ]
