# Generated by Django 4.2.5 on 2023-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('detalles', models.CharField(max_length=100)),
                ('presupuesto', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
