# Generated by Django 4.2.5 on 2023-12-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0002_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tratado',
            field=models.BooleanField(default=False),
        ),
    ]
