# Generated by Django 4.2.4 on 2023-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0003_artista_cancion_genero_entidadmusical_cancion_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='duracion',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
