# Generated by Django 4.2.5 on 2023-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0003_solicitud_tratado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='canciones',
            field=models.ManyToManyField(to='sonbuenos.cancion'),
        ),
    ]
