# Generated by Django 4.2.4 on 2023-08-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0004_artista_nacionalidad_cancion_duracion_cancion_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonbuenos',
            old_name='genero',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='entidadmusical',
            name='canciones',
        ),
        migrations.AddField(
            model_name='cancion',
            name='entidad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sonbuenos.entidadmusical'),
            preserve_default=False,
        ),
    ]
