# Generated by Django 4.2.5 on 2023-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonbuenos', '0004_solicitud_canciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='canciones',
            field=models.ManyToManyField(null=True, to='sonbuenos.cancion'),
        ),
    ]
